baseURL = "localhost:1313/test"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "targets"
theme = "hugo-theme-learn"
themesdir = "./themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/machellerogden/targets"
  description = "targets"
  author = "Mac Heller-Ogden"
  showVisitedLinks = true
  themeVariant = "targets"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "targets"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/machellerogden/targets"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
